### PR TITLE
Fix analyzer on staging

### PR DESCRIPTION
**Pull request by smacker**
Fix: #12

The main problem was incorrect dataServiceUrl.
But I updated code a little to be consistent with other analyzers.

### CODE REVIEW

**Comment by smacker** [comment]
I don't see maintainers file in this repo. So tag @meyskens & @rporres for review / merge.

**Comment by rporres** [comment]
Looks fine, thanks for fixing this. But why have you deleted `Gopkg.lock` file?

**Comment by meyskens** [comment]
@rporres https://github.com/src-d/lookout-terraform-analyzer/pull/13/files#diff-bd247e83efc3c45ae9e8c47233249f18
It is still there

**Comment by rporres** [comment]
so weird, this is the diff that GitHub shows...
image

**Pull request merged**
